tr building linux release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,6 +4,7 @@ version: 2.1
 
 orbs:
   win: circleci/windows@5.0
+  github-cli: circleci/github-cli@2.3.0
 
 # Orchestrate jobs using workflows
 # See: https://circleci.com/docs/configuration-reference/#workflows
@@ -41,7 +42,7 @@ commands:
               echo "releases only on github. skipping on bitbucket."
               circleci-agent step halt
             fi
-            echo "proceeding with building release on github"
+            echo "proceeding with circleci run"
       # checkout must be before mkdir, mkdir must be before sanity test 😬
       - checkout
       - run: mkdir -p ./out/make ./out/junit
@@ -58,49 +59,68 @@ jobs:
       - image: cimg/node:20.10.0
     steps:
       - steps-before
-      # - restore_cache:
-      #     key: dependency-B-linux-{{ checksum "package.json" }}
-      # - run: npm install
-      # - run: npm run test:ci
-      # - store_test_results:
-      #     path: out/junit
-      # - run:
-      #     name: Install OS specific
-      #     command: |
-      #       sudo apt-get update -y
-      #       # rpm only needed for MakerRpm
-      #       sudo apt-get install -y dpkg fakeroot rpm
-      #       # all of these only needed for running (in selftest)
-      #       sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 libatspi2.0-0 libdrm2 libgbm1 libasound2 libcups2 libatk1.0-0 libatk-bridge2.0-0 xvfb
-      #       # reduce dbus warning on linux selftest
-      #       sudo apt-get install -y dbus
-      #       sudo dbus-uuidgen --ensure
-      #       sudo service dbus start
-      # - save_cache:
-      #     key: dependency-B-linux-{{ checksum "package.json" }}
-      #     paths:
-      #       - ./node_modules
-      # - run: npm run make
-      # - run:
-      #     name: List store_artifacts
-      #     command: ls -lR ./out
-      # - run:
-      #     name: start mock display
-      #     background: true
-      #     command: Xvfb :99 -screen 0 1920x1080x24
-      # - run:
-      #     name: electron selftest (linux)
-      #     command: |
-      #       export DISPLAY=:99
-      #       ./out/neopic-linux-x64/neopic -selftest --disable-gpu
-      #       exitcode=$?
-      #       if [ $exitcode -ne 0 ]; then
-      #         echo "Failure or exit with code $exitcode"
-      #         exit $exitcode
-      #       fi
-      #       echo "selftest success"
-      # - store_artifacts:
-      #     path: out/make
+      - restore_cache:
+          key: dependency-B-linux-{{ checksum "package.json" }}
+      - run: npm install
+      - run: npm run test:ci
+      - store_test_results:
+          path: out/junit
+      - run:
+          name: Install OS specific
+          command: |
+            sudo apt-get update -y
+            # rpm only needed for MakerRpm
+            sudo apt-get install -y dpkg fakeroot rpm
+            # all of these only needed for running (in selftest)
+            sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 libatspi2.0-0 libdrm2 libgbm1 libasound2 libcups2 libatk1.0-0 libatk-bridge2.0-0 xvfb
+            # reduce dbus warning on linux selftest
+            sudo apt-get install -y dbus
+            sudo dbus-uuidgen --ensure
+            sudo service dbus start
+      - save_cache:
+          key: dependency-B-linux-{{ checksum "package.json" }}
+          paths:
+            - ./node_modules
+      - run: npm run make
+      - run:
+          name: List store_artifacts
+          command: ls -lR ./out
+      - run:
+          name: start mock display
+          background: true
+          command: Xvfb :99 -screen 0 1920x1080x24
+      - run:
+          name: electron selftest (linux)
+          command: |
+            export DISPLAY=:99
+            ./out/neopic-linux-x64/neopic -selftest --disable-gpu
+            exitcode=$?
+            if [ $exitcode -ne 0 ]; then
+              echo "Failure or exit with code $exitcode"
+              exit $exitcode
+            fi
+            echo "selftest success"
+      - store_artifacts:
+          path: out/make
+      - run:
+          name: release on tag release ONLY
+          command: |
+            if [[ "$CIRCLE_TAG" != release-* ]]; then
+              echo "release only with tag release-*. thus ending here for $CIRCLE_TAG."
+              circleci-agent step halt
+            fi
+            echo 'export RELEASE_VERSION_NUMBER="${CIRCLE_TAG#release-}"' >> "$BASH_ENV"
+            echo "proceeding with release on github"
+      - gh/release:
+          title: "${CIRCLE_TAG#release-}"
+          notes: "automated release by circleci"
+          # TODO after back to master
+          # filters:
+          #   branches:
+          #     only:
+          #       - master
+          notes-file: changelog.md
+          files: out/make/deb/x64/*.deb, out/make/rpm/x64/*.rpm
 
   build-macos:
     macos:
