config.yml env var testing2

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,6 +43,34 @@ workflows:
 # Reuse a sequence of steps
 # See: https://circleci.com/docs/configuration-reference/#workflows
 commands:
+  write-badge:
+    parameters:
+      json_file:
+        type: string
+      status:
+        type: string
+    steps:
+      - run:
+          name: "write badge-gist"
+          command: |
+            echo "Params: →→→ {{ json_file }} | {{  status  }}"
+            COLOR="unclear"
+            STATUS="unclear"
+            if [ "{{ status }}" == "PASS" ]; then
+            COLOR="brightgreen"
+            STATUS="pass"
+            elif [ "{{ status }}" == "FAIL" ]; then
+            COLOR="red"
+            STATUS="failed"
+            fi
+            LAST_RUN=$(TZ="Europe/Zurich" date '+%Y-%m-%d %H:%M:%S')
+            echo "{\"files\": { \"{{ json_file }}.json\" : {\"schemaVersion\": 1, \"label\": \"build\", \"message\": \"{{ status }}\", \"color\": \"$COLOR\", \"lastRun\": \"$LAST_RUN\"}}}" | tee status.json
+            curl -L -X PATCH \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d @status.json \
+            "https://api.github.com/gists/$GITHUB_GIST"
   steps-before:
     steps:
       - run:
@@ -64,20 +92,35 @@ commands:
   steps-after:
     steps:
       - run:
-          # i.e. resuilt-linux=PASS
           name: set PASS flag
           when: on_success
-          command: echo "export ${CIRCLE_JOB/build-/result_}=PASS" >> "$BASH_ENV"
+          command: |
+            echo "export THIS_RUN=PASS" >> "$BASH_ENV"
+            echo PASS > workspace/${CIRCLE_JOB/build-/result_}
       - run:
           name: set FAIL flag
           when: on_fail
-          command: echo "export ${CIRCLE_JOB/build-/result_}=FAIL" >> "$BASH_ENV"
+          command: |
+            echo "export THIS_RUN=FAIL" >> "$BASH_ENV"
+            echo PASS > workspace/${CIRCLE_JOB/build-/result_}
+      - persist_to_workspace:
+          root: workspace
+          paths:
+            - workspace/${CIRCLE_JOB/build-/result_}
+      - attach_workspace:
+          at: /tmp/workspace
+      # - write-badge: # writes the singular-result badge
+      #     when: always
+      #     json_file: ${CIRCLE_JOB/build-/neopic-status-}
+      #     status: $THIS_RUN
       - run:
-          name: update-badge
+          name: update-global-badge
           when: always
           command: |
-            echo "UPDATE BADGE"
             cat $BASH_ENV
+            echo '----------------'
+            ll -lR /tmp/workspace
+
       - store_artifacts:
           path: out/make
       - run:
@@ -101,6 +144,9 @@ jobs:
     docker:
       - image: cimg/node:20.10.0
     steps:
+      - run: # TEMPTEMP
+          name: Fail the job
+          command: exit 1
       - steps-before
       - restore_cache:
           key: dependency-B-linux-{{ checksum "package.json" }}
